import { Request, Response } from 'express';
import bcrypt from 'bcrypt';
import jwt from 'jsonwebtoken';
import { createUser, findUserByUsername } from '../models/user.model';

/**
 * ====================================================================================
 * AUTHENTICATION CONTROLLER
 * Handles user registration and login logic.
 * ====================================================================================
 */

/**
 * Register a new user
 * @route POST /api/auth/register
 * Steps:
 * 1. Validate input (username, password required).
 * 2. Check if username already exists in DB.
 * 3. Hash the password using bcrypt for security.
 * 4. Save the new user to the database.
 */
export const register = async (req: Request, res: Response): Promise<void> => {
    const { username, password } = req.body;

    // 1. Input Validation
    if (!username || !password) {
        res.status(400).json({ message: 'Username and password are required' });
        return;
    }

    try {
        // 2. Check for existing user
        const existingUser = await findUserByUsername(username);
        if (existingUser) {
            res.status(400).json({ message: 'Username already exists' });
            return;
        }

        // 3. Hash Password (never store plain text passwords!)
        const hashedPassword = await bcrypt.hash(password, 10); // 10 is the salt rounds

        // 4. Create User
        await createUser({
            id: '', // ID is auto-generated by database
            username,
            password: hashedPassword,
            role: username === 'admin' ? 'admin' : 'user', // Simple role assignment logic for demo
        });

        res.status(201).json({ message: 'User registered successfully' });
    } catch (error) {
        console.error('Registration error:', error);
        res.status(500).json({ message: 'Internal server error' });
    }
};

/**
 * Login an existing user
 * @route POST /api/auth/login
 * Steps:
 * 1. Validate input.
 * 2. Find user by username.
 * 3. Compare provided password with stored hashed password.
 * 4. Generate a JWT token if authentication succeeds.
 */
export const login = async (req: Request, res: Response): Promise<void> => {
    const { username, password } = req.body;

    // 1. Input Validation
    if (!username || !password) {
        res.status(400).json({ message: 'Username and password are required' });
        return;
    }

    try {
        // 2. Find User
        const user = await findUserByUsername(username);
        if (!user) {
            res.status(401).json({ message: 'Invalid credentials' });
            return;
        }

        // 3. Verify Password
        const isPasswordValid = await bcrypt.compare(password, user.password);
        if (!isPasswordValid) {
            res.status(401).json({ message: 'Invalid credentials' });
            return;
        }

        // 4. Generate JWT Token
        // This token will be used for subsequent authenticated requests
        const token = jwt.sign(
            { id: user.id, username: user.username, role: user.role },
            process.env.JWT_SECRET || 'default_secret',
            { expiresIn: (process.env.JWT_EXPIRES_IN || '1h') as any }
        );

        res.status(200).json({
            message: 'Login successful',
            token,
            user: {
                id: user.id,
                username: user.username,
                role: user.role,
            },
        });
    } catch (error) {
        console.error('Login error:', error);
        res.status(500).json({ message: 'Internal server error' });
    }
};

