import { Request, Response } from 'express';
import bcrypt from 'bcrypt';
import { createUser, findUserByUsername } from '../models/user.model';

export const register = async (req: Request, res: Response): Promise<void> => {
    const { username, password } = req.body;

    if (!username || !password) {
        res.status(400).json({ message: 'Username and password are required' });
        return;
    }

    try {
        const existingUser = await findUserByUsername(username);
        if (existingUser) {
            res.status(400).json({ message: 'Username already exists' });
            return;
        }

        const hashedPassword = await bcrypt.hash(password, 10);
        await createUser({
            id: '', // ID is generated by database
            username,
            password: hashedPassword,
            role: 'user', // Default role for now
        });

        res.status(201).json({ message: 'User registered successfully' });
    } catch (error) {
        console.error('Registration error:', error);
        res.status(500).json({ message: 'Internal server error' });
    }
};
